name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: beeware/buildozer:latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK
      run: |
        buildozer -v android debug
