name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: uggi27/buildozer-action@v1.1.0
      with:
        buildozer-version: main
        target: android
        type: debug
